### ISSUE TITLE
Bricks the Nano S device

### ISSUE THREAD

**Issue by dafacto** [Zondax/ledger-spacemesh#22]
Trying to use the app on a Nano S bricks the device as soon as a transaction sign attempt is made. This is not the case with a Nano S Plus, for example.

**Comment by schinzelh** [comment]
Appears to be fixed with 0.0.10 / https://github.com/Zondax/ledger-spacemesh/pull/24

**Comment by abenso** [comment]
Yes, the issue should be resolved with version `0.0.10`

**Comment by abenso** [comment]
Yes, the issue should be resolved with version 0.0.10
